name: spendy

description: "A new Flutter project."

publish_to: 'none'

version: 0.1.0+1

environment:

  sdk: ^3.13.1

dependencies:

  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1

  intl: ^0.20.2

  fl_chart: ^1.1.1

  firebase_core: ^3.12.1

  cloud_firestore: ^5.6.5

  firebase_auth: ^5.5.1

  shared_preferences: ^2.5.5

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/spendy_icon.png"
